<a href="https://colab.research.google.com/github/imjunyoung404/ai-class-3-2/blob/main/ML_classfication_abalone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("/content/abalone.csv", index_col=0)
df

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
id                                                                 
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  Rings  
id                                         
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [8]:
df_encoded = pd.get_dummies(df, columns=['Sex'], drop_first=True)

In [9]:
X = df_encoded.drop('Rings', axis=1)  # 'ring' 열을 제외한 나머지 특성들
y = df_encoded['Rings']  # 'ring' 열을 타겟 변수로 사용

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)


In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [13]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.2516746411483254
[[ 0  5  0  0  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0 23  4  0  5  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0 29 18  4  9  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 27 30 20 34  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6 11 48 65  8  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5 25 84 34  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  9 63 46 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  5 49 42 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  3 38 36 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2 18 17 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2 16 10  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  6 12  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  

In [14]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.24210526315789474
[[ 0  0  3  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 30  7  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 23 27  6  5  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18 39 28 27  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5 14 58 52  9  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 11 32 64 40  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  6 16 49 45 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8 15 29 47 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  6 31 37 17  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  3 10 20 16  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3 11 13  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  4 11  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.261244019138756
[[ 0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  8  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5 11 16  6  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  6 27 17  7  4  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4 24 27 33 24  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  6 10 58 50 11  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  9 24 69 41  7  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  6 11 49 42 26  0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  4 10 31 41 32  0  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6 21 38 20  0  5  0  0  2  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  3 22 18  0  3  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  4 16  4  0  5  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3  9  5  0  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [16]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.18277511961722487
[[ 1  5  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  6  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  7 12  4  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  7  9 25 10  2  2  3  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  4 24 35 29 12  6  0  1  0  2  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  6 26 38 28 21  8  5  2  0  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2 11 32 33 30 14 11  8  3  4  2  1  0  0  0  1  0  0  0  0  0]
 [ 0  1  0  1  8 16 38 25 17 11  9  4  3  3  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  0  2  1  9 21 27 16 13 12  6  3  2  3  5  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  2  8 20 18  8 11 11  3  5  0  0  2  2  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  5  9  7  8  8  6  2  2  0  0  0  2  1  1  0  0  0  0  0]
 [ 0  0  0  0  0  3  2  3  5  8  3  2  3  2  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  4  3  3  3  0  2  0  2  2

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))



--- Radom Forest ---
0.23827751196172248
[[ 0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  7  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9 15 11  3  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  7 22 19 10  3  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 25 35 35  9  5  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  4 18 50 38 18  5  1  1  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  9 35 44 41 12  5  4  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  3 18 35 41 23  9  3  2  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  8 33 41 24  4  4  1  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  2  6 18 37 14  4  4  0  1  1  1  0  3  0  1  0  0  0  0]
 [ 0  0  0  0  0  4  7 12 13  5  5  2  0  0  1  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  5  7  5  1  2  2  3  4  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  1  3  6  4  3  3  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  2